import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={
            "max-md:h-screen max-md:overflow-hidden max-md:overflow-y-auto relative"
          }
        >
          {children}
        </body>
      </html>
  );
}
